### ISSUE TITLE
Crash Xiaomi

### ISSUE THREAD

**Issue by CarlosIDM** [galadril/Xam.Shell.Badge#34] opened 2022-03-18 22:00 UTC
I am testing the plugin in a Tab of the xamarin forms shell, but when executing the app on a physical device xiaomi android 10, poco x3 the app crashes

android.runtime.JavaProxyThrowable: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Google.Android.Material.BottomNavigation.BottomNavigationView'.
  at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00029] in <00c315a988634383b446eff646084784>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00000] in <00c315a988634383b446eff646084784>:0 
  at Android.Views.ViewGroup.GetChildAt (System.Int32 index) [0x00022] in <31d0ff079d2b4470befd40c15e1fed76>:0 
  at BadgeShellItemRenderer.ApplyBadge (System.Int32 itemId, System.String badgeText, Xamarin.Forms.Color badgeBg, Xamarin.Forms.Color textColor) [0x00009] in <7c155dfa00254a6b807af47465d23410>:0 
  at BadgeShellItemRenderer.UpdateBadge (Xamarin.Forms.ShellSection item, System.Int32 index) [0x0001a] in <7c155dfa00254a6b807af47465d23410>:0 
  at BadgeShellItemRenderer.InitBadges () [0x0003d] in <7c155dfa00254a6b807af47465d23410>:0 
  at Xamarin.Forms.Device+<>c_DisplayClass43_0.<InvokeOnMainThreadAsync>g_wrapAction|0 () [0x00000] in <361de4fd2138410a8d727d37bccf8e01>:0 
  at Xamarin.Forms.Device+<>c_DisplayClass42_0`1[T].<InvokeOnMainThreadAsync>b_0 () [0x00000] in <361de4fd2138410a8d727d37bccf8e01>:0 
--- End of stack trace from previous location where exception was thrown ---

  at AsyncAwaitBestPractices.SafeFireAndForgetExtensions.HandleSafeFireAndForget[TException] (System.Threading.Tasks.Task task, System.Boolean continueOnCapturedContext, System.Action`1[T] onException) [0x0006f] in <8039d31f240b405abc8435fcdbcacf54>:0 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <1b39a03c32ec46258a7821e202e0269f>:0 
  at Android.App.SyncContext+<>c_DisplayClass2_0.<Post>b_0 () [0x00000] in <31d0ff079d2b4470befd40c15e1fed76>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <31d0ff079d2b4470befd40c15e1fed76>:0 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <31d0ff079d2b4470befd40c15e1fed76>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.47(intptr,intptr)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by SnowPowerCore** [comment] 2022-03-23 12:41
Hello, @CarlosIDM, thank you for the report. I'll look into it on the coming days.

**Comment by SnowPowerCore** [comment] 2022-04-25 21:20
@CarlosIDM, hello, if possible, please confirm this issue is resolved within the recent 1.0.20.

**Comment by nellogaudino** [comment] 2022-04-29 17:51
Hi, the issue is not resolved, when I publish app in Release mode on Xiomi device, the app crash.
Thank you.

LOG: MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] Android.Runtime.JavaProxyThrowable: Exception of type 'Android.Runtime.JavaProxyThrowable' was thrown.
[MonoDroid]   --- End of managed Android.Runtime.JavaProxyThrowable stack trace ---
[MonoDroid] android.runtime.JavaProxyThrowable: System.MissingMethodException: Default constructor not found for type Xam.Shell.Badge.Droid.Renderers.BadgeShellRenderer

**Comment by SnowPowerCore** [comment] 2022-04-29 18:06
Hello, @nellogaudino, i think, it's a different problem, you should create new issue about it.

**Comment by nellogaudino** [comment] 2022-04-29 18:31
Done, thank you.

**Comment by SnowPowerCore** [comment] 2022-04-30 17:08
Hello, @CarlosIDM, so far i can confirm that this issue is resolved by 1.0.20 version, so i'm closing this topic. If you experience any other problems, feel free to create new PRs.

**Closed by SnowPowerCore** 2022-04-30 17:08 UTC
